/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in machine
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table machine.city
	 */
	public static final com.qunar.coach.machine.dao.model.tables.City CITY = com.qunar.coach.machine.dao.model.tables.City.CITY;

	/**
	 * The table machine.identity_card
	 */
	public static final com.qunar.coach.machine.dao.model.tables.IdentityCard IDENTITY_CARD = com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD;

	/**
	 * The table machine.Machine
	 */
	public static final com.qunar.coach.machine.dao.model.tables.Machine MACHINE = com.qunar.coach.machine.dao.model.tables.Machine.MACHINE;

	/**
	 * The table machine.machine_info
	 */
	public static final com.qunar.coach.machine.dao.model.tables.MachineInfo MACHINE_INFO = com.qunar.coach.machine.dao.model.tables.MachineInfo.MACHINE_INFO;

	/**
	 * The table machine.province
	 */
	public static final com.qunar.coach.machine.dao.model.tables.Province PROVINCE = com.qunar.coach.machine.dao.model.tables.Province.PROVINCE;

	/**
	 * The table machine.shenzhen_ticket_info
	 */
	public static final com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo SHENZHEN_TICKET_INFO = com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO;

	/**
	 * The table machine.station
	 */
	public static final com.qunar.coach.machine.dao.model.tables.Station STATION = com.qunar.coach.machine.dao.model.tables.Station.STATION;

	/**
	 * The table machine.ticket_print_info
	 */
	public static final com.qunar.coach.machine.dao.model.tables.TicketPrintInfo TICKET_PRINT_INFO = com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO;
}
