/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdentityCardRecord extends org.jooq.impl.UpdatableRecordImpl<com.qunar.coach.machine.dao.model.tables.records.IdentityCardRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Byte, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -117956144;

	/**
	 * Setter for <code>coach.identity_card.id</code>.
	 */
	public IdentityCardRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>coach.identity_card.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>coach.identity_card.card_id</code>. 身份证号
	 */
	public IdentityCardRecord setCardId(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>coach.identity_card.card_id</code>. 身份证号
	 */
	public java.lang.String getCardId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>coach.identity_card.name</code>. 姓名
	 */
	public IdentityCardRecord setName(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>coach.identity_card.name</code>. 姓名
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>coach.identity_card.nation</code>. 民族
	 */
	public IdentityCardRecord setNation(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>coach.identity_card.nation</code>. 民族
	 */
	public java.lang.String getNation() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>coach.identity_card.birth_date</code>. 出生日期
	 */
	public IdentityCardRecord setBirthDate(java.sql.Timestamp value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>coach.identity_card.birth_date</code>. 出生日期
	 */
	public java.sql.Timestamp getBirthDate() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>coach.identity_card.address</code>. 地址
	 */
	public IdentityCardRecord setAddress(java.lang.String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>coach.identity_card.address</code>. 地址
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>coach.identity_card.sex</code>. 性别
	 */
	public IdentityCardRecord setSex(java.lang.Byte value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>coach.identity_card.sex</code>. 性别
	 */
	public java.lang.Byte getSex() {
		return (java.lang.Byte) getValue(6);
	}

	/**
	 * Setter for <code>coach.identity_card.modify_time</code>.
	 */
	public IdentityCardRecord setModifyTime(java.sql.Timestamp value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>coach.identity_card.modify_time</code>.
	 */
	public java.sql.Timestamp getModifyTime() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>coach.identity_card.create_time</code>.
	 */
	public IdentityCardRecord setCreateTime(java.sql.Timestamp value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>coach.identity_card.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Byte, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Byte, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.CARD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.NATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.BIRTH_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field7() {
		return com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.SEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.MODIFY_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCardId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getNation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getBirthDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value7() {
		return getSex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getModifyTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord value2(java.lang.String value) {
		setCardId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord value4(java.lang.String value) {
		setNation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord value5(java.sql.Timestamp value) {
		setBirthDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord value6(java.lang.String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord value7(java.lang.Byte value) {
		setSex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord value8(java.sql.Timestamp value) {
		setModifyTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord value9(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdentityCardRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.sql.Timestamp value5, java.lang.String value6, java.lang.Byte value7, java.sql.Timestamp value8, java.sql.Timestamp value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IdentityCardRecord
	 */
	public IdentityCardRecord() {
		super(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD);
	}

	/**
	 * Create a detached, initialised IdentityCardRecord
	 */
	public IdentityCardRecord(java.lang.Integer id, java.lang.String cardId, java.lang.String name, java.lang.String nation, java.sql.Timestamp birthDate, java.lang.String address, java.lang.Byte sex, java.sql.Timestamp modifyTime, java.sql.Timestamp createTime) {
		super(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD);

		setValue(0, id);
		setValue(1, cardId);
		setValue(2, name);
		setValue(3, nation);
		setValue(4, birthDate);
		setValue(5, address);
		setValue(6, sex);
		setValue(7, modifyTime);
		setValue(8, createTime);
	}
}
