/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineRecord extends org.jooq.impl.UpdatableRecordImpl<com.qunar.coach.machine.dao.model.tables.records.MachineRecord> implements org.jooq.Record22<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, com.qunar.coach.machine.core.model.MachineStatus, java.lang.Byte, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1187366719;

	/**
	 * Setter for <code>coach.Machine.id</code>.
	 */
	public MachineRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>coach.Machine.machine_print_mode</code>.
	 */
	public MachineRecord setMachinePrintMode(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.machine_print_mode</code>.
	 */
	public java.lang.String getMachinePrintMode() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>coach.Machine.ip</code>.
	 */
	public MachineRecord setIp(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.ip</code>.
	 */
	public java.lang.String getIp() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>coach.Machine.province</code>.
	 */
	public MachineRecord setProvince(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.province</code>.
	 */
	public java.lang.String getProvince() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>coach.Machine.city</code>.
	 */
	public MachineRecord setCity(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.city</code>.
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>coach.Machine.station_info</code>.
	 */
	public MachineRecord setStationInfo(java.lang.String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.station_info</code>.
	 */
	public java.lang.String getStationInfo() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>coach.Machine.login</code>.
	 */
	public MachineRecord setLogin(com.qunar.coach.machine.core.model.MachineStatus value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.login</code>.
	 */
	public com.qunar.coach.machine.core.model.MachineStatus getLogin() {
		return (com.qunar.coach.machine.core.model.MachineStatus) getValue(6);
	}

	/**
	 * Setter for <code>coach.Machine.group_number</code>.
	 */
	public MachineRecord setGroupNumber(java.lang.Byte value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.group_number</code>.
	 */
	public java.lang.Byte getGroupNumber() {
		return (java.lang.Byte) getValue(7);
	}

	/**
	 * Setter for <code>coach.Machine.ticket_mode</code>.
	 */
	public MachineRecord setTicketMode(java.lang.String value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.ticket_mode</code>.
	 */
	public java.lang.String getTicketMode() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>coach.Machine.print_times</code>.
	 */
	public MachineRecord setPrintTimes(java.lang.Integer value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.print_times</code>.
	 */
	public java.lang.Integer getPrintTimes() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>coach.Machine.suc_times</code>.
	 */
	public MachineRecord setSucTimes(java.lang.Integer value) {
		setValue(10, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.suc_times</code>.
	 */
	public java.lang.Integer getSucTimes() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>coach.Machine.failed_times</code>.
	 */
	public MachineRecord setFailedTimes(java.lang.Integer value) {
		setValue(11, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.failed_times</code>.
	 */
	public java.lang.Integer getFailedTimes() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>coach.Machine.paper_number</code>.
	 */
	public MachineRecord setPaperNumber(java.lang.Integer value) {
		setValue(12, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.paper_number</code>.
	 */
	public java.lang.Integer getPaperNumber() {
		return (java.lang.Integer) getValue(12);
	}

	/**
	 * Setter for <code>coach.Machine.paper_used</code>.
	 */
	public MachineRecord setPaperUsed(java.lang.Integer value) {
		setValue(13, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.paper_used</code>.
	 */
	public java.lang.Integer getPaperUsed() {
		return (java.lang.Integer) getValue(13);
	}

	/**
	 * Setter for <code>coach.Machine.user_id</code>.
	 */
	public MachineRecord setUserId(java.lang.String value) {
		setValue(14, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>coach.Machine.version</code>.
	 */
	public MachineRecord setVersion(java.lang.String value) {
		setValue(15, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.version</code>.
	 */
	public java.lang.String getVersion() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>coach.Machine.pass_word</code>.
	 */
	public MachineRecord setPassWord(java.lang.String value) {
		setValue(16, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.pass_word</code>.
	 */
	public java.lang.String getPassWord() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>coach.Machine.modify_time</code>.
	 */
	public MachineRecord setModifyTime(java.sql.Timestamp value) {
		setValue(17, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.modify_time</code>.
	 */
	public java.sql.Timestamp getModifyTime() {
		return (java.sql.Timestamp) getValue(17);
	}

	/**
	 * Setter for <code>coach.Machine.create_time</code>.
	 */
	public MachineRecord setCreateTime(java.sql.Timestamp value) {
		setValue(18, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(18);
	}

	/**
	 * Setter for <code>coach.Machine.sync_time</code>.
	 */
	public MachineRecord setSyncTime(java.sql.Timestamp value) {
		setValue(19, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.sync_time</code>.
	 */
	public java.sql.Timestamp getSyncTime() {
		return (java.sql.Timestamp) getValue(19);
	}

	/**
	 * Setter for <code>coach.Machine.device_id</code>.
	 */
	public MachineRecord setDeviceId(java.lang.String value) {
		setValue(20, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.device_id</code>.
	 */
	public java.lang.String getDeviceId() {
		return (java.lang.String) getValue(20);
	}

	/**
	 * Setter for <code>coach.Machine.sequence_number</code>.
	 */
	public MachineRecord setSequenceNumber(java.lang.Integer value) {
		setValue(21, value);
		return this;
	}

	/**
	 * Getter for <code>coach.Machine.sequence_number</code>.
	 */
	public java.lang.Integer getSequenceNumber() {
		return (java.lang.Integer) getValue(21);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record22 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, com.qunar.coach.machine.core.model.MachineStatus, java.lang.Byte, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row22) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, com.qunar.coach.machine.core.model.MachineStatus, java.lang.Byte, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row22) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.MACHINE_PRINT_MODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.IP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PROVINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.STATION_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.qunar.coach.machine.core.model.MachineStatus> field7() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.LOGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field8() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.GROUP_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.TICKET_MODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PRINT_TIMES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.SUC_TIMES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.FAILED_TIMES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field13() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PAPER_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field14() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PAPER_USED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field17() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PASS_WORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field18() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.MODIFY_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field19() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field20() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.SYNC_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field21() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.DEVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field22() {
		return com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.SEQUENCE_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getMachinePrintMode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getIp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getProvince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getStationInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qunar.coach.machine.core.model.MachineStatus value7() {
		return getLogin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value8() {
		return getGroupNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getTicketMode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getPrintTimes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getSucTimes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getFailedTimes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value13() {
		return getPaperNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value14() {
		return getPaperUsed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value17() {
		return getPassWord();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value18() {
		return getModifyTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value19() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value20() {
		return getSyncTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value21() {
		return getDeviceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value22() {
		return getSequenceNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value2(java.lang.String value) {
		setMachinePrintMode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value3(java.lang.String value) {
		setIp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value4(java.lang.String value) {
		setProvince(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value5(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value6(java.lang.String value) {
		setStationInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value7(com.qunar.coach.machine.core.model.MachineStatus value) {
		setLogin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value8(java.lang.Byte value) {
		setGroupNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value9(java.lang.String value) {
		setTicketMode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value10(java.lang.Integer value) {
		setPrintTimes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value11(java.lang.Integer value) {
		setSucTimes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value12(java.lang.Integer value) {
		setFailedTimes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value13(java.lang.Integer value) {
		setPaperNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value14(java.lang.Integer value) {
		setPaperUsed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value15(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value16(java.lang.String value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value17(java.lang.String value) {
		setPassWord(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value18(java.sql.Timestamp value) {
		setModifyTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value19(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value20(java.sql.Timestamp value) {
		setSyncTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value21(java.lang.String value) {
		setDeviceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord value22(java.lang.Integer value) {
		setSequenceNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, com.qunar.coach.machine.core.model.MachineStatus value7, java.lang.Byte value8, java.lang.String value9, java.lang.Integer value10, java.lang.Integer value11, java.lang.Integer value12, java.lang.Integer value13, java.lang.Integer value14, java.lang.String value15, java.lang.String value16, java.lang.String value17, java.sql.Timestamp value18, java.sql.Timestamp value19, java.sql.Timestamp value20, java.lang.String value21, java.lang.Integer value22) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MachineRecord
	 */
	public MachineRecord() {
		super(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE);
	}

	/**
	 * Create a detached, initialised MachineRecord
	 */
	public MachineRecord(java.lang.Integer id, java.lang.String machinePrintMode, java.lang.String ip, java.lang.String province, java.lang.String city, java.lang.String stationInfo, com.qunar.coach.machine.core.model.MachineStatus login, java.lang.Byte groupNumber, java.lang.String ticketMode, java.lang.Integer printTimes, java.lang.Integer sucTimes, java.lang.Integer failedTimes, java.lang.Integer paperNumber, java.lang.Integer paperUsed, java.lang.String userId, java.lang.String version, java.lang.String passWord, java.sql.Timestamp modifyTime, java.sql.Timestamp createTime, java.sql.Timestamp syncTime, java.lang.String deviceId, java.lang.Integer sequenceNumber) {
		super(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE);

		setValue(0, id);
		setValue(1, machinePrintMode);
		setValue(2, ip);
		setValue(3, province);
		setValue(4, city);
		setValue(5, stationInfo);
		setValue(6, login);
		setValue(7, groupNumber);
		setValue(8, ticketMode);
		setValue(9, printTimes);
		setValue(10, sucTimes);
		setValue(11, failedTimes);
		setValue(12, paperNumber);
		setValue(13, paperUsed);
		setValue(14, userId);
		setValue(15, version);
		setValue(16, passWord);
		setValue(17, modifyTime);
		setValue(18, createTime);
		setValue(19, syncTime);
		setValue(20, deviceId);
		setValue(21, sequenceNumber);
	}
}
