/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineRecord extends org.jooq.impl.UpdatableRecordImpl<com.qunar.coach.machine.dao.model.tables.records.MachineRecord> {

	private static final long serialVersionUID = 1111401775;

	/**
	 * Setter for <code>machine.Machine.id</code>.
	 */
	public MachineRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>machine.Machine.machine_print_mode</code>.
	 */
	public MachineRecord setMachinePrintMode(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.machine_print_mode</code>.
	 */
	public java.lang.String getMachinePrintMode() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>machine.Machine.ip</code>.
	 */
	public MachineRecord setIp(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.ip</code>.
	 */
	public java.lang.String getIp() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>machine.Machine.province</code>.
	 */
	public MachineRecord setProvince(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.province</code>.
	 */
	public java.lang.String getProvince() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>machine.Machine.city</code>.
	 */
	public MachineRecord setCity(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.city</code>.
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>machine.Machine.station_info</code>.
	 */
	public MachineRecord setStationInfo(java.lang.String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.station_info</code>.
	 */
	public java.lang.String getStationInfo() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>machine.Machine.login</code>.
	 */
	public MachineRecord setLogin(com.qunar.coach.machine.core.model.MachineStatus value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.login</code>.
	 */
	public com.qunar.coach.machine.core.model.MachineStatus getLogin() {
		return (com.qunar.coach.machine.core.model.MachineStatus) getValue(6);
	}

	/**
	 * Setter for <code>machine.Machine.group_number</code>.
	 */
	public MachineRecord setGroupNumber(java.lang.Byte value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.group_number</code>.
	 */
	public java.lang.Byte getGroupNumber() {
		return (java.lang.Byte) getValue(7);
	}

	/**
	 * Setter for <code>machine.Machine.ticket_mode</code>.
	 */
	public MachineRecord setTicketMode(java.lang.String value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.ticket_mode</code>.
	 */
	public java.lang.String getTicketMode() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>machine.Machine.print_times</code>.
	 */
	public MachineRecord setPrintTimes(java.lang.Integer value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.print_times</code>.
	 */
	public java.lang.Integer getPrintTimes() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>machine.Machine.suc_times</code>.
	 */
	public MachineRecord setSucTimes(java.lang.Integer value) {
		setValue(10, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.suc_times</code>.
	 */
	public java.lang.Integer getSucTimes() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>machine.Machine.failed_times</code>.
	 */
	public MachineRecord setFailedTimes(java.lang.Integer value) {
		setValue(11, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.failed_times</code>.
	 */
	public java.lang.Integer getFailedTimes() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>machine.Machine.scan_suc_times</code>.
	 */
	public MachineRecord setScanSucTimes(java.lang.Integer value) {
		setValue(12, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.scan_suc_times</code>.
	 */
	public java.lang.Integer getScanSucTimes() {
		return (java.lang.Integer) getValue(12);
	}

	/**
	 * Setter for <code>machine.Machine.scan_failed_times</code>.
	 */
	public MachineRecord setScanFailedTimes(java.lang.Integer value) {
		setValue(13, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.scan_failed_times</code>.
	 */
	public java.lang.Integer getScanFailedTimes() {
		return (java.lang.Integer) getValue(13);
	}

	/**
	 * Setter for <code>machine.Machine.paper_number</code>.
	 */
	public MachineRecord setPaperNumber(java.lang.Integer value) {
		setValue(14, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.paper_number</code>.
	 */
	public java.lang.Integer getPaperNumber() {
		return (java.lang.Integer) getValue(14);
	}

	/**
	 * Setter for <code>machine.Machine.paper_used</code>.
	 */
	public MachineRecord setPaperUsed(java.lang.Integer value) {
		setValue(15, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.paper_used</code>.
	 */
	public java.lang.Integer getPaperUsed() {
		return (java.lang.Integer) getValue(15);
	}

	/**
	 * Setter for <code>machine.Machine.user_id</code>.
	 */
	public MachineRecord setUserId(java.lang.String value) {
		setValue(16, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>machine.Machine.version</code>.
	 */
	public MachineRecord setVersion(java.lang.String value) {
		setValue(17, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.version</code>.
	 */
	public java.lang.String getVersion() {
		return (java.lang.String) getValue(17);
	}

	/**
	 * Setter for <code>machine.Machine.pass_word</code>.
	 */
	public MachineRecord setPassWord(java.lang.String value) {
		setValue(18, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.pass_word</code>.
	 */
	public java.lang.String getPassWord() {
		return (java.lang.String) getValue(18);
	}

	/**
	 * Setter for <code>machine.Machine.modify_time</code>.
	 */
	public MachineRecord setModifyTime(java.sql.Timestamp value) {
		setValue(19, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.modify_time</code>.
	 */
	public java.sql.Timestamp getModifyTime() {
		return (java.sql.Timestamp) getValue(19);
	}

	/**
	 * Setter for <code>machine.Machine.create_time</code>.
	 */
	public MachineRecord setCreateTime(java.sql.Timestamp value) {
		setValue(20, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(20);
	}

	/**
	 * Setter for <code>machine.Machine.sync_time</code>.
	 */
	public MachineRecord setSyncTime(java.sql.Timestamp value) {
		setValue(21, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.sync_time</code>.
	 */
	public java.sql.Timestamp getSyncTime() {
		return (java.sql.Timestamp) getValue(21);
	}

	/**
	 * Setter for <code>machine.Machine.device_id</code>.
	 */
	public MachineRecord setDeviceId(java.lang.String value) {
		setValue(22, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.device_id</code>.
	 */
	public java.lang.String getDeviceId() {
		return (java.lang.String) getValue(22);
	}

	/**
	 * Setter for <code>machine.Machine.sequence_number</code>.
	 */
	public MachineRecord setSequenceNumber(java.lang.Integer value) {
		setValue(23, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.sequence_number</code>.
	 */
	public java.lang.Integer getSequenceNumber() {
		return (java.lang.Integer) getValue(23);
	}

	/**
	 * Setter for <code>machine.Machine.maintenance</code>.
	 */
	public MachineRecord setMaintenance(java.lang.Integer value) {
		setValue(24, value);
		return this;
	}

	/**
	 * Getter for <code>machine.Machine.maintenance</code>.
	 */
	public java.lang.Integer getMaintenance() {
		return (java.lang.Integer) getValue(24);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MachineRecord
	 */
	public MachineRecord() {
		super(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE);
	}

	/**
	 * Create a detached, initialised MachineRecord
	 */
	public MachineRecord(java.lang.Integer id, java.lang.String machinePrintMode, java.lang.String ip, java.lang.String province, java.lang.String city, java.lang.String stationInfo, com.qunar.coach.machine.core.model.MachineStatus login, java.lang.Byte groupNumber, java.lang.String ticketMode, java.lang.Integer printTimes, java.lang.Integer sucTimes, java.lang.Integer failedTimes, java.lang.Integer scanSucTimes, java.lang.Integer scanFailedTimes, java.lang.Integer paperNumber, java.lang.Integer paperUsed, java.lang.String userId, java.lang.String version, java.lang.String passWord, java.sql.Timestamp modifyTime, java.sql.Timestamp createTime, java.sql.Timestamp syncTime, java.lang.String deviceId, java.lang.Integer sequenceNumber, java.lang.Integer maintenance) {
		super(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE);

		setValue(0, id);
		setValue(1, machinePrintMode);
		setValue(2, ip);
		setValue(3, province);
		setValue(4, city);
		setValue(5, stationInfo);
		setValue(6, login);
		setValue(7, groupNumber);
		setValue(8, ticketMode);
		setValue(9, printTimes);
		setValue(10, sucTimes);
		setValue(11, failedTimes);
		setValue(12, scanSucTimes);
		setValue(13, scanFailedTimes);
		setValue(14, paperNumber);
		setValue(15, paperUsed);
		setValue(16, userId);
		setValue(17, version);
		setValue(18, passWord);
		setValue(19, modifyTime);
		setValue(20, createTime);
		setValue(21, syncTime);
		setValue(22, deviceId);
		setValue(23, sequenceNumber);
		setValue(24, maintenance);
	}
}
