/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShenzhenTicketInfoRecord extends org.jooq.impl.UpdatableRecordImpl<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord> implements org.jooq.Record17<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 403721321;

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.id</code>.
	 */
	public ShenzhenTicketInfoRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.ticket_number</code>.
	 */
	public ShenzhenTicketInfoRecord setTicketNumber(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.ticket_number</code>.
	 */
	public java.lang.String getTicketNumber() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.line</code>.
	 */
	public ShenzhenTicketInfoRecord setLine(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.line</code>.
	 */
	public java.lang.String getLine() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.take_place</code>.
	 */
	public ShenzhenTicketInfoRecord setTakePlace(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.take_place</code>.
	 */
	public java.lang.String getTakePlace() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.destination</code>.
	 */
	public ShenzhenTicketInfoRecord setDestination(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.destination</code>.
	 */
	public java.lang.String getDestination() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.start_time</code>.
	 */
	public ShenzhenTicketInfoRecord setStartTime(java.sql.Timestamp value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.start_time</code>.
	 */
	public java.sql.Timestamp getStartTime() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.coach_type</code>.
	 */
	public ShenzhenTicketInfoRecord setCoachType(java.lang.String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.coach_type</code>.
	 */
	public java.lang.String getCoachType() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.seat_number</code>.
	 */
	public ShenzhenTicketInfoRecord setSeatNumber(java.lang.String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.seat_number</code>.
	 */
	public java.lang.String getSeatNumber() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.price</code>.
	 */
	public ShenzhenTicketInfoRecord setPrice(java.math.BigDecimal value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.price</code>.
	 */
	public java.math.BigDecimal getPrice() {
		return (java.math.BigDecimal) getValue(8);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.check_port_number</code>.
	 */
	public ShenzhenTicketInfoRecord setCheckPortNumber(java.lang.String value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.check_port_number</code>.
	 */
	public java.lang.String getCheckPortNumber() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.sell_ticket_place</code>.
	 */
	public ShenzhenTicketInfoRecord setSellTicketPlace(java.lang.String value) {
		setValue(10, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.sell_ticket_place</code>.
	 */
	public java.lang.String getSellTicketPlace() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.coach_number</code>.
	 */
	public ShenzhenTicketInfoRecord setCoachNumber(java.lang.String value) {
		setValue(11, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.coach_number</code>.
	 */
	public java.lang.String getCoachNumber() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.ticket_id</code>.
	 */
	public ShenzhenTicketInfoRecord setTicketId(java.lang.String value) {
		setValue(12, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.ticket_id</code>.
	 */
	public java.lang.String getTicketId() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.passenger_name</code>.
	 */
	public ShenzhenTicketInfoRecord setPassengerName(java.lang.String value) {
		setValue(13, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.passenger_name</code>.
	 */
	public java.lang.String getPassengerName() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.card_id</code>.
	 */
	public ShenzhenTicketInfoRecord setCardId(java.lang.String value) {
		setValue(14, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.card_id</code>.
	 */
	public java.lang.String getCardId() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.modify_time</code>.
	 */
	public ShenzhenTicketInfoRecord setModifyTime(java.sql.Timestamp value) {
		setValue(15, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.modify_time</code>.
	 */
	public java.sql.Timestamp getModifyTime() {
		return (java.sql.Timestamp) getValue(15);
	}

	/**
	 * Setter for <code>machine.shenzhen_ticket_info.create_time</code>.
	 */
	public ShenzhenTicketInfoRecord setCreateTime(java.sql.Timestamp value) {
		setValue(16, value);
		return this;
	}

	/**
	 * Getter for <code>machine.shenzhen_ticket_info.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record17 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row17) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row17) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.TICKET_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.LINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.TAKE_PLACE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.DESTINATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.COACH_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.SEAT_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field9() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.CHECK_PORT_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.SELL_TICKET_PLACE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.COACH_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.TICKET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.PASSENGER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.CARD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field16() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.MODIFY_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field17() {
		return com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTicketNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLine();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTakePlace();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDestination();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCoachType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getSeatNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value9() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getCheckPortNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getSellTicketPlace();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getCoachNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getTicketId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getPassengerName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getCardId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value16() {
		return getModifyTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value17() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value2(java.lang.String value) {
		setTicketNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value3(java.lang.String value) {
		setLine(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value4(java.lang.String value) {
		setTakePlace(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value5(java.lang.String value) {
		setDestination(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value6(java.sql.Timestamp value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value7(java.lang.String value) {
		setCoachType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value8(java.lang.String value) {
		setSeatNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value9(java.math.BigDecimal value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value10(java.lang.String value) {
		setCheckPortNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value11(java.lang.String value) {
		setSellTicketPlace(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value12(java.lang.String value) {
		setCoachNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value13(java.lang.String value) {
		setTicketId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value14(java.lang.String value) {
		setPassengerName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value15(java.lang.String value) {
		setCardId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value16(java.sql.Timestamp value) {
		setModifyTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord value17(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShenzhenTicketInfoRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.sql.Timestamp value6, java.lang.String value7, java.lang.String value8, java.math.BigDecimal value9, java.lang.String value10, java.lang.String value11, java.lang.String value12, java.lang.String value13, java.lang.String value14, java.lang.String value15, java.sql.Timestamp value16, java.sql.Timestamp value17) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ShenzhenTicketInfoRecord
	 */
	public ShenzhenTicketInfoRecord() {
		super(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO);
	}

	/**
	 * Create a detached, initialised ShenzhenTicketInfoRecord
	 */
	public ShenzhenTicketInfoRecord(java.lang.Integer id, java.lang.String ticketNumber, java.lang.String line, java.lang.String takePlace, java.lang.String destination, java.sql.Timestamp startTime, java.lang.String coachType, java.lang.String seatNumber, java.math.BigDecimal price, java.lang.String checkPortNumber, java.lang.String sellTicketPlace, java.lang.String coachNumber, java.lang.String ticketId, java.lang.String passengerName, java.lang.String cardId, java.sql.Timestamp modifyTime, java.sql.Timestamp createTime) {
		super(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO);

		setValue(0, id);
		setValue(1, ticketNumber);
		setValue(2, line);
		setValue(3, takePlace);
		setValue(4, destination);
		setValue(5, startTime);
		setValue(6, coachType);
		setValue(7, seatNumber);
		setValue(8, price);
		setValue(9, checkPortNumber);
		setValue(10, sellTicketPlace);
		setValue(11, coachNumber);
		setValue(12, ticketId);
		setValue(13, passengerName);
		setValue(14, cardId);
		setValue(15, modifyTime);
		setValue(16, createTime);
	}
}
