/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StationRecord extends org.jooq.impl.UpdatableRecordImpl<com.qunar.coach.machine.dao.model.tables.records.StationRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1585687890;

	/**
	 * Setter for <code>coach.station.id</code>.
	 */
	public StationRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>coach.station.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>coach.station.station_name</code>.
	 */
	public StationRecord setStationName(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>coach.station.station_name</code>.
	 */
	public java.lang.String getStationName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>coach.station.city_id</code>.
	 */
	public StationRecord setCityId(java.lang.Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>coach.station.city_id</code>.
	 */
	public java.lang.Integer getCityId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.qunar.coach.machine.dao.model.tables.Station.STATION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.qunar.coach.machine.dao.model.tables.Station.STATION.STATION_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.qunar.coach.machine.dao.model.tables.Station.STATION.CITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getStationName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StationRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StationRecord value2(java.lang.String value) {
		setStationName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StationRecord value3(java.lang.Integer value) {
		setCityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StationRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StationRecord
	 */
	public StationRecord() {
		super(com.qunar.coach.machine.dao.model.tables.Station.STATION);
	}

	/**
	 * Create a detached, initialised StationRecord
	 */
	public StationRecord(java.lang.Integer id, java.lang.String stationName, java.lang.Integer cityId) {
		super(com.qunar.coach.machine.dao.model.tables.Station.STATION);

		setValue(0, id);
		setValue(1, stationName);
		setValue(2, cityId);
	}
}
