/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketPrintInfoRecord extends org.jooq.impl.UpdatableRecordImpl<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.Integer, com.qunar.coach.machine.core.TicketStatus, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = -246231927;

	/**
	 * Setter for <code>coach.ticket_print_info.id</code>.
	 */
	public TicketPrintInfoRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>coach.ticket_print_info.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>coach.ticket_print_info.ticket_id</code>.
	 */
	public TicketPrintInfoRecord setTicketId(java.lang.Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>coach.ticket_print_info.ticket_id</code>.
	 */
	public java.lang.Integer getTicketId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>coach.ticket_print_info.status</code>.
	 */
	public TicketPrintInfoRecord setStatus(com.qunar.coach.machine.core.TicketStatus value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>coach.ticket_print_info.status</code>.
	 */
	public com.qunar.coach.machine.core.TicketStatus getStatus() {
		return (com.qunar.coach.machine.core.TicketStatus) getValue(2);
	}

	/**
	 * Setter for <code>coach.ticket_print_info.print_machine_id</code>.
	 */
	public TicketPrintInfoRecord setPrintMachineId(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>coach.ticket_print_info.print_machine_id</code>.
	 */
	public java.lang.String getPrintMachineId() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>coach.ticket_print_info.modify_time</code>.
	 */
	public TicketPrintInfoRecord setModifyTime(java.sql.Timestamp value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>coach.ticket_print_info.modify_time</code>.
	 */
	public java.sql.Timestamp getModifyTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>coach.ticket_print_info.create_time</code>.
	 */
	public TicketPrintInfoRecord setCreateTime(java.sql.Timestamp value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>coach.ticket_print_info.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>coach.ticket_print_info.print_id</code>.
	 */
	public TicketPrintInfoRecord setPrintId(java.lang.String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>coach.ticket_print_info.print_id</code>.
	 */
	public java.lang.String getPrintId() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, com.qunar.coach.machine.core.TicketStatus, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, com.qunar.coach.machine.core.TicketStatus, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO.TICKET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.qunar.coach.machine.core.TicketStatus> field3() {
		return com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO.PRINT_MACHINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO.MODIFY_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO.PRINT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getTicketId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qunar.coach.machine.core.TicketStatus value3() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPrintMachineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getModifyTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getPrintId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketPrintInfoRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketPrintInfoRecord value2(java.lang.Integer value) {
		setTicketId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketPrintInfoRecord value3(com.qunar.coach.machine.core.TicketStatus value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketPrintInfoRecord value4(java.lang.String value) {
		setPrintMachineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketPrintInfoRecord value5(java.sql.Timestamp value) {
		setModifyTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketPrintInfoRecord value6(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketPrintInfoRecord value7(java.lang.String value) {
		setPrintId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketPrintInfoRecord values(java.lang.Integer value1, java.lang.Integer value2, com.qunar.coach.machine.core.TicketStatus value3, java.lang.String value4, java.sql.Timestamp value5, java.sql.Timestamp value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TicketPrintInfoRecord
	 */
	public TicketPrintInfoRecord() {
		super(com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO);
	}

	/**
	 * Create a detached, initialised TicketPrintInfoRecord
	 */
	public TicketPrintInfoRecord(java.lang.Integer id, java.lang.Integer ticketId, com.qunar.coach.machine.core.TicketStatus status, java.lang.String printMachineId, java.sql.Timestamp modifyTime, java.sql.Timestamp createTime, java.lang.String printId) {
		super(com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO);

		setValue(0, id);
		setValue(1, ticketId);
		setValue(2, status);
		setValue(3, printMachineId);
		setValue(4, modifyTime);
		setValue(5, createTime);
		setValue(6, printId);
	}
}
