/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineInfo implements java.io.Serializable {

	private static final long serialVersionUID = -631540613;

	private java.lang.Integer id;
	private java.lang.Long    machineId;
	private java.lang.Integer printMode;

	public MachineInfo() {}

	public MachineInfo(
		java.lang.Integer id,
		java.lang.Long    machineId,
		java.lang.Integer printMode
	) {
		this.id = id;
		this.machineId = machineId;
		this.printMode = printMode;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public MachineInfo setId(java.lang.Integer id) {
		this.id = id;
		return this;
	}

	public java.lang.Long getMachineId() {
		return this.machineId;
	}

	public MachineInfo setMachineId(java.lang.Long machineId) {
		this.machineId = machineId;
		return this;
	}

	public java.lang.Integer getPrintMode() {
		return this.printMode;
	}

	public MachineInfo setPrintMode(java.lang.Integer printMode) {
		this.printMode = printMode;
		return this;
	}
}
