/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Station implements java.io.Serializable {

	private static final long serialVersionUID = -1605304183;

	private java.lang.Integer id;
	private java.lang.String  stationName;
	private java.lang.Integer cityId;

	public Station() {}

	public Station(
		java.lang.Integer id,
		java.lang.String  stationName,
		java.lang.Integer cityId
	) {
		this.id = id;
		this.stationName = stationName;
		this.cityId = cityId;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public Station setId(java.lang.Integer id) {
		this.id = id;
		return this;
	}

	public java.lang.String getStationName() {
		return this.stationName;
	}

	public Station setStationName(java.lang.String stationName) {
		this.stationName = stationName;
		return this;
	}

	public java.lang.Integer getCityId() {
		return this.cityId;
	}

	public Station setCityId(java.lang.Integer cityId) {
		this.cityId = cityId;
		return this;
	}
}
