/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketPrintInfo implements java.io.Serializable {

	private static final long serialVersionUID = 958752255;

	private java.lang.Integer                         id;
	private java.lang.Integer                         ticketId;
	private com.qunar.coach.machine.core.TicketStatus status;
	private java.lang.String                          printMachineId;
	private java.sql.Timestamp                        modifyTime;
	private java.sql.Timestamp                        createTime;
	private java.lang.String                          printId;

	public TicketPrintInfo() {}

	public TicketPrintInfo(
		java.lang.Integer                         id,
		java.lang.Integer                         ticketId,
		com.qunar.coach.machine.core.TicketStatus status,
		java.lang.String                          printMachineId,
		java.sql.Timestamp                        modifyTime,
		java.sql.Timestamp                        createTime,
		java.lang.String                          printId
	) {
		this.id = id;
		this.ticketId = ticketId;
		this.status = status;
		this.printMachineId = printMachineId;
		this.modifyTime = modifyTime;
		this.createTime = createTime;
		this.printId = printId;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public TicketPrintInfo setId(java.lang.Integer id) {
		this.id = id;
		return this;
	}

	public java.lang.Integer getTicketId() {
		return this.ticketId;
	}

	public TicketPrintInfo setTicketId(java.lang.Integer ticketId) {
		this.ticketId = ticketId;
		return this;
	}

	public com.qunar.coach.machine.core.TicketStatus getStatus() {
		return this.status;
	}

	public TicketPrintInfo setStatus(com.qunar.coach.machine.core.TicketStatus status) {
		this.status = status;
		return this;
	}

	public java.lang.String getPrintMachineId() {
		return this.printMachineId;
	}

	public TicketPrintInfo setPrintMachineId(java.lang.String printMachineId) {
		this.printMachineId = printMachineId;
		return this;
	}

	public java.sql.Timestamp getModifyTime() {
		return this.modifyTime;
	}

	public TicketPrintInfo setModifyTime(java.sql.Timestamp modifyTime) {
		this.modifyTime = modifyTime;
		return this;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public TicketPrintInfo setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
		return this;
	}

	public java.lang.String getPrintId() {
		return this.printId;
	}

	public TicketPrintInfo setPrintId(java.lang.String printId) {
		this.printId = printId;
		return this;
	}
}
