/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityDao extends org.jooq.impl.DAOImpl<com.qunar.coach.machine.dao.model.tables.records.CityRecord, com.qunar.coach.machine.dao.model.tables.pojos.City, java.lang.Integer> {

	/**
	 * Create a new CityDao without any configuration
	 */
	public CityDao() {
		super(com.qunar.coach.machine.dao.model.tables.City.CITY, com.qunar.coach.machine.dao.model.tables.pojos.City.class);
	}

	/**
	 * Create a new CityDao with an attached configuration
	 */
	public CityDao(org.jooq.Configuration configuration) {
		super(com.qunar.coach.machine.dao.model.tables.City.CITY, com.qunar.coach.machine.dao.model.tables.pojos.City.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.qunar.coach.machine.dao.model.tables.pojos.City object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.City> fetchById(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.City.CITY.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.qunar.coach.machine.dao.model.tables.pojos.City fetchOneById(java.lang.Integer value) {
		return fetchOne(com.qunar.coach.machine.dao.model.tables.City.CITY.ID, value);
	}

	/**
	 * Fetch records that have <code>province IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.City> fetchByProvince(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.City.CITY.PROVINCE, values);
	}

	/**
	 * Fetch records that have <code>city_name IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.City> fetchByCityName(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.City.CITY.CITY_NAME, values);
	}
}
