/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdentityCardDao extends org.jooq.impl.DAOImpl<com.qunar.coach.machine.dao.model.tables.records.IdentityCardRecord, com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard, java.lang.Integer> {

	/**
	 * Create a new IdentityCardDao without any configuration
	 */
	public IdentityCardDao() {
		super(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD, com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard.class);
	}

	/**
	 * Create a new IdentityCardDao with an attached configuration
	 */
	public IdentityCardDao(org.jooq.Configuration configuration) {
		super(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD, com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard> fetchById(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard fetchOneById(java.lang.Integer value) {
		return fetchOne(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.ID, value);
	}

	/**
	 * Fetch records that have <code>card_id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard> fetchByCardId(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.CARD_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>card_id = value</code>
	 */
	public com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard fetchOneByCardId(java.lang.String value) {
		return fetchOne(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.CARD_ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard> fetchByName(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.NAME, values);
	}

	/**
	 * Fetch records that have <code>nation IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard> fetchByNation(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.NATION, values);
	}

	/**
	 * Fetch records that have <code>birth_date IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard> fetchByBirthDate(java.sql.Timestamp... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.BIRTH_DATE, values);
	}

	/**
	 * Fetch records that have <code>address IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard> fetchByAddress(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.ADDRESS, values);
	}

	/**
	 * Fetch records that have <code>sex IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard> fetchBySex(java.lang.Byte... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.SEX, values);
	}

	/**
	 * Fetch records that have <code>modify_time IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard> fetchByModifyTime(java.sql.Timestamp... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.MODIFY_TIME, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.IdentityCard> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.IdentityCard.IDENTITY_CARD.CREATE_TIME, values);
	}
}
