/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineInfoDao extends org.jooq.impl.DAOImpl<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord, com.qunar.coach.machine.dao.model.tables.pojos.MachineInfo, java.lang.Integer> {

	/**
	 * Create a new MachineInfoDao without any configuration
	 */
	public MachineInfoDao() {
		super(com.qunar.coach.machine.dao.model.tables.MachineInfo.MACHINE_INFO, com.qunar.coach.machine.dao.model.tables.pojos.MachineInfo.class);
	}

	/**
	 * Create a new MachineInfoDao with an attached configuration
	 */
	public MachineInfoDao(org.jooq.Configuration configuration) {
		super(com.qunar.coach.machine.dao.model.tables.MachineInfo.MACHINE_INFO, com.qunar.coach.machine.dao.model.tables.pojos.MachineInfo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.qunar.coach.machine.dao.model.tables.pojos.MachineInfo object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.MachineInfo> fetchById(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.MachineInfo.MACHINE_INFO.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.qunar.coach.machine.dao.model.tables.pojos.MachineInfo fetchOneById(java.lang.Integer value) {
		return fetchOne(com.qunar.coach.machine.dao.model.tables.MachineInfo.MACHINE_INFO.ID, value);
	}

	/**
	 * Fetch records that have <code>machine_id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.MachineInfo> fetchByMachineId(java.lang.Long... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.MachineInfo.MACHINE_INFO.MACHINE_ID, values);
	}

	/**
	 * Fetch records that have <code>print_mode IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.MachineInfo> fetchByPrintMode(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.MachineInfo.MACHINE_INFO.PRINT_MODE, values);
	}
}
