/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineDao extends org.jooq.impl.DAOImpl<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, com.qunar.coach.machine.dao.model.tables.pojos.Machine, java.lang.Integer> {

	/**
	 * Create a new MachineDao without any configuration
	 */
	public MachineDao() {
		super(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE, com.qunar.coach.machine.dao.model.tables.pojos.Machine.class);
	}

	/**
	 * Create a new MachineDao with an attached configuration
	 */
	public MachineDao(org.jooq.Configuration configuration) {
		super(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE, com.qunar.coach.machine.dao.model.tables.pojos.Machine.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.qunar.coach.machine.dao.model.tables.pojos.Machine object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchById(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.qunar.coach.machine.dao.model.tables.pojos.Machine fetchOneById(java.lang.Integer value) {
		return fetchOne(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.ID, value);
	}

	/**
	 * Fetch records that have <code>machine_print_mode IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByMachinePrintMode(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.MACHINE_PRINT_MODE, values);
	}

	/**
	 * Fetch records that have <code>ip IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByIp(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.IP, values);
	}

	/**
	 * Fetch records that have <code>province IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByProvince(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PROVINCE, values);
	}

	/**
	 * Fetch records that have <code>city IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByCity(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.CITY, values);
	}

	/**
	 * Fetch records that have <code>station_info IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByStationInfo(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.STATION_INFO, values);
	}

	/**
	 * Fetch records that have <code>login IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByLogin(com.qunar.coach.machine.core.model.MachineStatus... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.LOGIN, values);
	}

	/**
	 * Fetch records that have <code>group_number IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByGroupNumber(java.lang.Byte... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.GROUP_NUMBER, values);
	}

	/**
	 * Fetch records that have <code>ticket_mode IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByTicketMode(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.TICKET_MODE, values);
	}

	/**
	 * Fetch records that have <code>print_times IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByPrintTimes(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PRINT_TIMES, values);
	}

	/**
	 * Fetch records that have <code>suc_times IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchBySucTimes(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.SUC_TIMES, values);
	}

	/**
	 * Fetch records that have <code>failed_times IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByFailedTimes(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.FAILED_TIMES, values);
	}

	/**
	 * Fetch records that have <code>paper_number IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByPaperNumber(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PAPER_NUMBER, values);
	}

	/**
	 * Fetch records that have <code>paper_used IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByPaperUsed(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PAPER_USED, values);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByUserId(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>version IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByVersion(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.VERSION, values);
	}

	/**
	 * Fetch records that have <code>pass_word IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByPassWord(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.PASS_WORD, values);
	}

	/**
	 * Fetch records that have <code>modify_time IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByModifyTime(java.sql.Timestamp... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.MODIFY_TIME, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.CREATE_TIME, values);
	}

	/**
	 * Fetch records that have <code>sync_time IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchBySyncTime(java.sql.Timestamp... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.SYNC_TIME, values);
	}

	/**
	 * Fetch records that have <code>device_id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchByDeviceId(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.DEVICE_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>device_id = value</code>
	 */
	public com.qunar.coach.machine.dao.model.tables.pojos.Machine fetchOneByDeviceId(java.lang.String value) {
		return fetchOne(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.DEVICE_ID, value);
	}

	/**
	 * Fetch records that have <code>sequence_number IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.Machine> fetchBySequenceNumber(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.Machine.MACHINE.SEQUENCE_NUMBER, values);
	}
}
