/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShenzhenTicketInfoDao extends org.jooq.impl.DAOImpl<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo, java.lang.Integer> {

	/**
	 * Create a new ShenzhenTicketInfoDao without any configuration
	 */
	public ShenzhenTicketInfoDao() {
		super(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO, com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo.class);
	}

	/**
	 * Create a new ShenzhenTicketInfoDao with an attached configuration
	 */
	public ShenzhenTicketInfoDao(org.jooq.Configuration configuration) {
		super(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO, com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchById(java.lang.Integer... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo fetchOneById(java.lang.Integer value) {
		return fetchOne(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.ID, value);
	}

	/**
	 * Fetch records that have <code>ticket_number IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByTicketNumber(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.TICKET_NUMBER, values);
	}

	/**
	 * Fetch a unique record that has <code>ticket_number = value</code>
	 */
	public com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo fetchOneByTicketNumber(java.lang.String value) {
		return fetchOne(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.TICKET_NUMBER, value);
	}

	/**
	 * Fetch records that have <code>line IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByLine(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.LINE, values);
	}

	/**
	 * Fetch records that have <code>take_place IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByTakePlace(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.TAKE_PLACE, values);
	}

	/**
	 * Fetch records that have <code>destination IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByDestination(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.DESTINATION, values);
	}

	/**
	 * Fetch records that have <code>start_time IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByStartTime(java.sql.Timestamp... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.START_TIME, values);
	}

	/**
	 * Fetch records that have <code>coach_type IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByCoachType(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.COACH_TYPE, values);
	}

	/**
	 * Fetch records that have <code>seat_number IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchBySeatNumber(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.SEAT_NUMBER, values);
	}

	/**
	 * Fetch records that have <code>price IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByPrice(java.math.BigDecimal... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.PRICE, values);
	}

	/**
	 * Fetch records that have <code>check_port_number IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByCheckPortNumber(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.CHECK_PORT_NUMBER, values);
	}

	/**
	 * Fetch records that have <code>sell_ticket_place IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchBySellTicketPlace(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.SELL_TICKET_PLACE, values);
	}

	/**
	 * Fetch records that have <code>coach_number IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByCoachNumber(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.COACH_NUMBER, values);
	}

	/**
	 * Fetch records that have <code>ticket_id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByTicketId(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.TICKET_ID, values);
	}

	/**
	 * Fetch records that have <code>passenger_name IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByPassengerName(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.PASSENGER_NAME, values);
	}

	/**
	 * Fetch records that have <code>card_id IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByCardId(java.lang.String... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.CARD_ID, values);
	}

	/**
	 * Fetch records that have <code>modify_time IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByModifyTime(java.sql.Timestamp... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.MODIFY_TIME, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.qunar.coach.machine.dao.model.tables.pojos.ShenzhenTicketInfo> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO.CREATE_TIME, values);
	}
}
