/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City extends org.jooq.impl.TableImpl<com.qunar.coach.machine.dao.model.tables.records.CityRecord> {

	private static final long serialVersionUID = -299581526;

	/**
	 * The singleton instance of <code>coach.city</code>
	 */
	public static final com.qunar.coach.machine.dao.model.tables.City CITY = new com.qunar.coach.machine.dao.model.tables.City();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.qunar.coach.machine.dao.model.tables.records.CityRecord> getRecordType() {
		return com.qunar.coach.machine.dao.model.tables.records.CityRecord.class;
	}

	/**
	 * The column <code>coach.city.id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.CityRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>coach.city.province</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.CityRecord, java.lang.Integer> PROVINCE = createField("province", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>coach.city.city_name</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.CityRecord, java.lang.String> CITY_NAME = createField("city_name", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * Create a <code>coach.city</code> table reference
	 */
	public City() {
		this("city", null);
	}

	/**
	 * Create an aliased <code>coach.city</code> table reference
	 */
	public City(java.lang.String alias) {
		this(alias, com.qunar.coach.machine.dao.model.tables.City.CITY);
	}

	private City(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.CityRecord> aliased) {
		this(alias, aliased, null);
	}

	private City(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.CityRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.qunar.coach.machine.dao.model.Coach.COACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.qunar.coach.machine.dao.model.tables.records.CityRecord, java.lang.Integer> getIdentity() {
		return com.qunar.coach.machine.dao.model.Keys.IDENTITY_CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.CityRecord> getPrimaryKey() {
		return com.qunar.coach.machine.dao.model.Keys.KEY_CITY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.CityRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.CityRecord>>asList(com.qunar.coach.machine.dao.model.Keys.KEY_CITY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qunar.coach.machine.dao.model.tables.City as(java.lang.String alias) {
		return new com.qunar.coach.machine.dao.model.tables.City(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.qunar.coach.machine.dao.model.tables.City rename(java.lang.String name) {
		return new com.qunar.coach.machine.dao.model.tables.City(name, null);
	}
}
