/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineInfo extends org.jooq.impl.TableImpl<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord> {

	private static final long serialVersionUID = 1466492214;

	/**
	 * The singleton instance of <code>coach.machine_info</code>
	 */
	public static final com.qunar.coach.machine.dao.model.tables.MachineInfo MACHINE_INFO = new com.qunar.coach.machine.dao.model.tables.MachineInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord> getRecordType() {
		return com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord.class;
	}

	/**
	 * The column <code>coach.machine_info.id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>coach.machine_info.machine_id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord, java.lang.Long> MACHINE_ID = createField("machine_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>coach.machine_info.print_mode</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord, java.lang.Integer> PRINT_MODE = createField("print_mode", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>coach.machine_info</code> table reference
	 */
	public MachineInfo() {
		this("machine_info", null);
	}

	/**
	 * Create an aliased <code>coach.machine_info</code> table reference
	 */
	public MachineInfo(java.lang.String alias) {
		this(alias, com.qunar.coach.machine.dao.model.tables.MachineInfo.MACHINE_INFO);
	}

	private MachineInfo(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private MachineInfo(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.qunar.coach.machine.dao.model.Coach.COACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord> getPrimaryKey() {
		return com.qunar.coach.machine.dao.model.Keys.KEY_MACHINE_INFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.MachineInfoRecord>>asList(com.qunar.coach.machine.dao.model.Keys.KEY_MACHINE_INFO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qunar.coach.machine.dao.model.tables.MachineInfo as(java.lang.String alias) {
		return new com.qunar.coach.machine.dao.model.tables.MachineInfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.qunar.coach.machine.dao.model.tables.MachineInfo rename(java.lang.String name) {
		return new com.qunar.coach.machine.dao.model.tables.MachineInfo(name, null);
	}
}
