/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Machine extends org.jooq.impl.TableImpl<com.qunar.coach.machine.dao.model.tables.records.MachineRecord> {

	private static final long serialVersionUID = -1298948369;

	/**
	 * The singleton instance of <code>coach.Machine</code>
	 */
	public static final com.qunar.coach.machine.dao.model.tables.Machine MACHINE = new com.qunar.coach.machine.dao.model.tables.Machine();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.qunar.coach.machine.dao.model.tables.records.MachineRecord> getRecordType() {
		return com.qunar.coach.machine.dao.model.tables.records.MachineRecord.class;
	}

	/**
	 * The column <code>coach.Machine.id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>coach.Machine.machine_print_mode</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> MACHINE_PRINT_MODE = createField("machine_print_mode", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>coach.Machine.ip</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> IP = createField("ip", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>coach.Machine.province</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> PROVINCE = createField("province", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>coach.Machine.city</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>coach.Machine.station_info</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> STATION_INFO = createField("station_info", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>coach.Machine.login</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, com.qunar.coach.machine.core.model.MachineStatus> LOGIN = createField("login", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "", new com.qunar.coach.machine.dao.converter.MachineStatusConverter());

	/**
	 * The column <code>coach.Machine.group_number</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.Byte> GROUP_NUMBER = createField("group_number", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * The column <code>coach.Machine.ticket_mode</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> TICKET_MODE = createField("ticket_mode", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>coach.Machine.print_times</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.Integer> PRINT_TIMES = createField("print_times", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>coach.Machine.suc_times</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.Integer> SUC_TIMES = createField("suc_times", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>coach.Machine.failed_times</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.Integer> FAILED_TIMES = createField("failed_times", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>coach.Machine.paper_number</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.Integer> PAPER_NUMBER = createField("paper_number", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>coach.Machine.paper_used</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.Integer> PAPER_USED = createField("paper_used", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>coach.Machine.user_id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>coach.Machine.version</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>coach.Machine.pass_word</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> PASS_WORD = createField("pass_word", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>coach.Machine.modify_time</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.sql.Timestamp> MODIFY_TIME = createField("modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>coach.Machine.create_time</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>coach.Machine.sync_time</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.sql.Timestamp> SYNC_TIME = createField("sync_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>coach.Machine.device_id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.String> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>coach.Machine.sequence_number</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.Integer> SEQUENCE_NUMBER = createField("sequence_number", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>coach.Machine</code> table reference
	 */
	public Machine() {
		this("Machine", null);
	}

	/**
	 * Create an aliased <code>coach.Machine</code> table reference
	 */
	public Machine(java.lang.String alias) {
		this(alias, com.qunar.coach.machine.dao.model.tables.Machine.MACHINE);
	}

	private Machine(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.MachineRecord> aliased) {
		this(alias, aliased, null);
	}

	private Machine(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.MachineRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.qunar.coach.machine.dao.model.Coach.COACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.qunar.coach.machine.dao.model.tables.records.MachineRecord, java.lang.Integer> getIdentity() {
		return com.qunar.coach.machine.dao.model.Keys.IDENTITY_MACHINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.MachineRecord> getPrimaryKey() {
		return com.qunar.coach.machine.dao.model.Keys.KEY_MACHINE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.MachineRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.MachineRecord>>asList(com.qunar.coach.machine.dao.model.Keys.KEY_MACHINE_PRIMARY, com.qunar.coach.machine.dao.model.Keys.KEY_MACHINE_DEVICE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qunar.coach.machine.dao.model.tables.Machine as(java.lang.String alias) {
		return new com.qunar.coach.machine.dao.model.tables.Machine(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.qunar.coach.machine.dao.model.tables.Machine rename(java.lang.String name) {
		return new com.qunar.coach.machine.dao.model.tables.Machine(name, null);
	}
}
