/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShenzhenTicketInfo extends org.jooq.impl.TableImpl<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord> {

	private static final long serialVersionUID = 437610921;

	/**
	 * The singleton instance of <code>machine.shenzhen_ticket_info</code>
	 */
	public static final com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo SHENZHEN_TICKET_INFO = new com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord> getRecordType() {
		return com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord.class;
	}

	/**
	 * The column <code>machine.shenzhen_ticket_info.id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.ticket_number</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> TICKET_NUMBER = createField("ticket_number", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.line</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> LINE = createField("line", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.take_place</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> TAKE_PLACE = createField("take_place", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.destination</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> DESTINATION = createField("destination", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.start_time</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.sql.Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.coach_type</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> COACH_TYPE = createField("coach_type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.seat_number</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> SEAT_NUMBER = createField("seat_number", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.price</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.math.BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.DECIMAL.precision(8, 1), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.check_port_number</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> CHECK_PORT_NUMBER = createField("check_port_number", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.sell_ticket_place</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> SELL_TICKET_PLACE = createField("sell_ticket_place", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.coach_number</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> COACH_NUMBER = createField("coach_number", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.ticket_id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> TICKET_ID = createField("ticket_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.passenger_name</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> PASSENGER_NAME = createField("passenger_name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.card_id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.String> CARD_ID = createField("card_id", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.modify_time</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.sql.Timestamp> MODIFY_TIME = createField("modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>machine.shenzhen_ticket_info.create_time</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>machine.shenzhen_ticket_info</code> table reference
	 */
	public ShenzhenTicketInfo() {
		this("shenzhen_ticket_info", null);
	}

	/**
	 * Create an aliased <code>machine.shenzhen_ticket_info</code> table reference
	 */
	public ShenzhenTicketInfo(java.lang.String alias) {
		this(alias, com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo.SHENZHEN_TICKET_INFO);
	}

	private ShenzhenTicketInfo(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private ShenzhenTicketInfo(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.qunar.coach.machine.dao.model.Machine.MACHINE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord, java.lang.Integer> getIdentity() {
		return com.qunar.coach.machine.dao.model.Keys.IDENTITY_SHENZHEN_TICKET_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord> getPrimaryKey() {
		return com.qunar.coach.machine.dao.model.Keys.KEY_SHENZHEN_TICKET_INFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.ShenzhenTicketInfoRecord>>asList(com.qunar.coach.machine.dao.model.Keys.KEY_SHENZHEN_TICKET_INFO_PRIMARY, com.qunar.coach.machine.dao.model.Keys.KEY_SHENZHEN_TICKET_INFO_TICKET_ID_IDX);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo as(java.lang.String alias) {
		return new com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo rename(java.lang.String name) {
		return new com.qunar.coach.machine.dao.model.tables.ShenzhenTicketInfo(name, null);
	}
}
