/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Station extends org.jooq.impl.TableImpl<com.qunar.coach.machine.dao.model.tables.records.StationRecord> {

	private static final long serialVersionUID = 1761446555;

	/**
	 * The singleton instance of <code>coach.station</code>
	 */
	public static final com.qunar.coach.machine.dao.model.tables.Station STATION = new com.qunar.coach.machine.dao.model.tables.Station();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.qunar.coach.machine.dao.model.tables.records.StationRecord> getRecordType() {
		return com.qunar.coach.machine.dao.model.tables.records.StationRecord.class;
	}

	/**
	 * The column <code>coach.station.id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.StationRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>coach.station.station_name</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.StationRecord, java.lang.String> STATION_NAME = createField("station_name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>coach.station.city_id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.StationRecord, java.lang.Integer> CITY_ID = createField("city_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>coach.station</code> table reference
	 */
	public Station() {
		this("station", null);
	}

	/**
	 * Create an aliased <code>coach.station</code> table reference
	 */
	public Station(java.lang.String alias) {
		this(alias, com.qunar.coach.machine.dao.model.tables.Station.STATION);
	}

	private Station(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.StationRecord> aliased) {
		this(alias, aliased, null);
	}

	private Station(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.StationRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.qunar.coach.machine.dao.model.Coach.COACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.StationRecord> getPrimaryKey() {
		return com.qunar.coach.machine.dao.model.Keys.KEY_STATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.StationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.StationRecord>>asList(com.qunar.coach.machine.dao.model.Keys.KEY_STATION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qunar.coach.machine.dao.model.tables.Station as(java.lang.String alias) {
		return new com.qunar.coach.machine.dao.model.tables.Station(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.qunar.coach.machine.dao.model.tables.Station rename(java.lang.String name) {
		return new com.qunar.coach.machine.dao.model.tables.Station(name, null);
	}
}
