/**
 * This class is generated by jOOQ
 */
package com.qunar.coach.machine.dao.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketPrintInfo extends org.jooq.impl.TableImpl<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord> {

	private static final long serialVersionUID = -1862791102;

	/**
	 * The singleton instance of <code>coach.ticket_print_info</code>
	 */
	public static final com.qunar.coach.machine.dao.model.tables.TicketPrintInfo TICKET_PRINT_INFO = new com.qunar.coach.machine.dao.model.tables.TicketPrintInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord> getRecordType() {
		return com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord.class;
	}

	/**
	 * The column <code>coach.ticket_print_info.id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>coach.ticket_print_info.ticket_id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord, java.lang.Integer> TICKET_ID = createField("ticket_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>coach.ticket_print_info.status</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord, com.qunar.coach.machine.core.TicketStatus> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "", new com.qunar.coach.machine.dao.converter.TicketStatusConverter());

	/**
	 * The column <code>coach.ticket_print_info.print_machine_id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord, java.lang.String> PRINT_MACHINE_ID = createField("print_machine_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>coach.ticket_print_info.modify_time</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord, java.sql.Timestamp> MODIFY_TIME = createField("modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>coach.ticket_print_info.create_time</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>coach.ticket_print_info.print_id</code>.
	 */
	public final org.jooq.TableField<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord, java.lang.String> PRINT_ID = createField("print_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * Create a <code>coach.ticket_print_info</code> table reference
	 */
	public TicketPrintInfo() {
		this("ticket_print_info", null);
	}

	/**
	 * Create an aliased <code>coach.ticket_print_info</code> table reference
	 */
	public TicketPrintInfo(java.lang.String alias) {
		this(alias, com.qunar.coach.machine.dao.model.tables.TicketPrintInfo.TICKET_PRINT_INFO);
	}

	private TicketPrintInfo(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private TicketPrintInfo(java.lang.String alias, org.jooq.Table<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.qunar.coach.machine.dao.model.Coach.COACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord, java.lang.Integer> getIdentity() {
		return com.qunar.coach.machine.dao.model.Keys.IDENTITY_TICKET_PRINT_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord> getPrimaryKey() {
		return com.qunar.coach.machine.dao.model.Keys.KEY_TICKET_PRINT_INFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.qunar.coach.machine.dao.model.tables.records.TicketPrintInfoRecord>>asList(com.qunar.coach.machine.dao.model.Keys.KEY_TICKET_PRINT_INFO_PRIMARY, com.qunar.coach.machine.dao.model.Keys.KEY_TICKET_PRINT_INFO_TICKET_ID_IDX);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qunar.coach.machine.dao.model.tables.TicketPrintInfo as(java.lang.String alias) {
		return new com.qunar.coach.machine.dao.model.tables.TicketPrintInfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.qunar.coach.machine.dao.model.tables.TicketPrintInfo rename(java.lang.String name) {
		return new com.qunar.coach.machine.dao.model.tables.TicketPrintInfo(name, null);
	}
}
